# -*- coding: utf-8 -*-
"""Colaboratory에 오신 것을 환영합니다의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mSXypv3sd9jNRWWR4lLtuXATd1uBmynZ
"""

def winCheck(win,num):
  win = False
  if score[0] == score[1] == score[2] == num:
      win = True
  elif score[3] == score[4] == score[5] == num:
      win = True
  elif score[1] == score[7] == score[8] == num:
      win = True
  elif score[0] == score[3] == score[6] == num:
      win = True
  elif score[1] == score[4] == score[7] == num:
      win = True
  elif score[2] == score[5] == score[8] == num:
      win = True
  elif score[0] == score[4] == score[8] == num:
      win = True
  elif score[2] == score[4] == score[6] == num:
      win = True
  return win

def EndGame(isGaming):
  isGaming = True
  if Owin:
    isGaming = False
  if Xwin:
    isGaming = False
  return isGaming

def OX(num):
  if num == 0:
    return " "
  elif num == 1:
    return "O"
  elif num == 2:
    return "X"


def sendTTT():
  print("tic-tac-toe")
  print("┌---┳---┳---┐")
  print("| %s | %s | %s |"%(OX(score[0]),OX(score[1]),OX(score[2])))
  print("┣---╋---╋---┫")
  print("| %s | %s | %s |"%(OX(score[3]),OX(score[4]),OX(score[5])))
  print("┣---╋---╋---┫")
  print("| %s | %s | %s |"%(OX(score[6]),OX(score[7]),OX(score[8])))
  print("└---┷---┷---┘")

score = [0,0,0,0,0,0,0,0,0]
isGaming = True
Owin = False
Xwin = False


while isGaming:
  sendTTT()

  inO = int(input("O-turn (1~9) : "))
  inO -= 1
  score[inO] = 1
  Owin = winCheck(Owin,1)
  isGaming = EndGame(isGaming)

  if isGaming:
    sendTTT()
    inX = int(input("X-turn (1~9) : "))
    inX -= 1
    score[inX] = 2
    Xwin = winCheck(Xwin,2)
    isGaming = EndGame(isGaming)

if not isGaming:
  sendTTT()
  if Owin:
    print("O - WIN")
  if Xwin:
    print("X - WIN")